[Feat] 파이어베이스 수정된 모델을 바탕으로 한 새로운 API 만들기
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #100
Opened 2022-07-30 07:37 UTC by yudonlee

## 🍑 관련 이슈
#98 

## 🍑 구현/변경 사항 및 이유
이슈사항에 보이는 대로, 기존에 pinCode와 userName에 의존해서 사용하던 관계를 문서아이디를 통한 참조로 바꾸었다.
TestViewController를 통해 함수 사용법을 익히면 될 것같다.

## 🍑 PR Point
command + shift + / 를 통해서 각 함수에 Document를 추가하여 사용하는 목적을 표기해놨습니다.
함수 overloading을 사용하여 여러가지 기능을 구현해두었습니다!

2022-07-30 14:31 UTC, YoonyoungL commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
p2;
앞 PR에도 남겨놨는데 fruitCategory를 Int로 하는 것이 좋아 보입니다!

2022-07-30 14:31 UTC, YoonyoungL commented on Gwayeon/Manager/FirebaseManager.swift
> +    func requestFruitInformation(uid: String, fruitBaseInfo: FruitBaseInfo, completion: @escaping (Result<String, Error>) -> Void) {
질문입니다 🙋🏻‍♀️
과일 추천하기 (+ 버튼 눌렀을 때)에서는
과일을 등록하고 추천평을 등록하는 함수 두개를 써야하는 건가요?

2022-07-30 17:30 UTC, coby5502 requested changes
헤헤...

2022-07-30 17:30 UTC, coby5502 commented on Gwayeon/Models/User.swift
> +    let friends, buyingFruits, recommends: [String]?
돌아왔구나 오태식이

2022-07-30 18:19 UTC, HeejiSohn approved these changes
:-)

2022-07-30 18:19 UTC, HeejiSohn commented on Gwayeon/FirebaseManagerTestUI/TestViewController.swift
> +        FirebaseManager.shared.requestFruitInformation(uid: uid, fruitBaseInfo: FruitBaseInfo(fruitCategory: "15", fruitName: "엄청난 한라봉", farmName: "유돈이네 한라봉", farmTelNumber: "010-4784-2949")) { resul
유동이네한라봉 직거래 한번 해봐야겠네요
개인정보주의!

2022-07-30 22:57 UTC, yudonlee commented on Gwayeon/Models/User.swift
> +    let friends, buyingFruits, recommends: [String]?
예리하군요👍

2022-07-30 23:00 UTC, yudonlee commented on Gwayeon/Manager/FirebaseManager.swift
> +    func requestFruitInformation(uid: String, fruitBaseInfo: FruitBaseInfo, completion: @escaping (Result<String, Error>) -> Void) {
우선적으로 분리된 task라고 생각했습니다. 과일을 추천하기 위해선, 그 과일을 산 뒤 그 과일을 등록해야 하니까요. 두가지를 한 함수안에 넣게 된다면 requestRecommend의 코드와 중복되기 때문에 분리해서 넣었습니다. 나중에 호출시에 선택적으로 하는게 맞다고 생각합니다.
더 좋은 의견 있다면 가감없이 말해주세요!

2022-07-31 04:20 UTC, yudonlee commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/99#discussion_r933923056 에서와 같이, 일단은 우선적으로 합친 뒤 enum까지 만들고 바꾸는 건 어떨까요!

2022-07-31 04:21 UTC, yudonlee commented
> 헤헤... async/await 를 쓸 건지, completion 을 쓸 건지도 얘기하봐야할거 같아요! async/await 코드가 더 알아보기 싶고, 예쁘지 않나? 싶네요!

그러니깐요, async/await도 좋긴 한데, 일단은 서버를 다완성해두고 다시 바꾸는건 어떤가요? 다들 서버와 연결해보고 싶을것 같아서요!

2022-07-31 05:12 UTC, coby5502 approved these changes

2022-07-31 05:56 UTC, YoonyoungL commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
확인했습니다!

2022-07-31 05:57 UTC, YoonyoungL commented on Gwayeon/Manager/FirebaseManager.swift
> +    func requestFruitInformation(uid: String, fruitBaseInfo: FruitBaseInfo, completion: @escaping (Result<String, Error>) -> Void) {
나중에 구현을 위해서 생각하다가 질문했습니다! 답변 갑사합니다~

2022-07-31 06:26 UTC, merged