Feat/21 homeview UI farm list
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #22
Opened 2022-07-19 02:53 UTC by coby5502

## 🟣 관련 이슈

#21 
## 🟣 구현/변경 사항 및 이유
- 농장 리스트 CollectionView로 구현
- 농장 리스트 셀 스타일 적용

## 🟣 PR Point

## 🟣 참고 사항

![simulator_screenshot_869BB9F2-A9CA-4B6F-8BBA-CA1C66C45597](https://user-images.githubusercontent.com/57849386/179654139-f25c9967-795d-4925-92c6-66c22c525c84.png)

2022-07-20 03:08 UTC, yudonlee requested changes
코비가 왜이렇게 짰을까 고민하면서 열심히 리뷰를 달아보았습니다.
굉장히 많은걸 구현한 만큼 신경쓰지 못한 부분도 있을것 같아 열심히 리뷰를 남겨보았습니다
다음 리뷰로 찾아오겠습니다 😁

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +    static let cellId = "FarmCollectionViewCell"
p4;
개인적으로 CollectionView에서 register할때 parameter name이 "identifier"이기 때문에 여기도 통일해주는게 좋을것 같습니다.
```swift
    static let identifier = "FarmCollectionViewCell"

```

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FruitCollectionViewCell.swift
> +    }
해당 부분을 한번도 사용해본적이 없는데, 어떠한 부분이며 어떤 용도로 쓰이는지 간단하게 알려줄수 있나요?

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FruitListView.swift
> +    func render() {
p4
render 보다는
```swift
private func setCollectionViewLayout() 
```
등 set 키워드로 레이아웃을 조절한다는 의미를 사용하는게 어떤가요? 아무래도 팀원들간에 통일이 필요해보입니다 ☺️

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FruitListView.swift
> +// MARK: - UICollectionViewDataSource
주석을 적극적으로 잘 사용했는데, 팀원들한테 공유해서 통일했으면 좋겠습니다.

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FruitListView.swift
> +        }
p3
저는 이렇게 사용해본적은 없어서 좋은지 나쁜진 모르겠지만 적어도 4줄을 2줄로 만들수 있는 코드는 소개해드리고 싶네요
```swift
guard let dequeuedCell = collectionView.dequeueReusableCell(withReuseIdentifier: FruitCollectionViewCell.cellId, for: indexPath) as? FruitCollectionViewCell else { 
return UICollectionViewCell()
}
```

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/FruitListView.swift
> +}
p3;
print만을 위해서 테스트하는 용도라면 빼는건 어떨까요?

2022-07-20 03:08 UTC, yudonlee commented on Gwayeon/Controllers/HomeViewController.swift
> +    }
p3
사용하지 않는 함수는 빼주시면 좋을것 같습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/HomeViewController.swift
> +    }
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FruitListView.swift
> +}
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FruitListView.swift
> +        }
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FruitListView.swift
> +// MARK: - UICollectionViewDataSource
넴

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FruitListView.swift
> +    func render() {
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FruitListView.swift
> +final class FruitListView: UIView {
넴

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +    }
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +    }()
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-20 03:31 UTC, coby5502 commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +    }()
[383f7a7](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/383f7a794d0209fd2e4942d6a4824e75a43d6e9f)
반영했습니다.

2022-07-21 02:10 UTC, YoonyoungL approved these changes

2022-07-21 02:21 UTC, coby5502 commented on Gwayeon/Globals/Extension/Color+Extension.swift
> +    static var grey001: UIColor {
같이 얘기해보고 나중에 변수명 짓는 것도 통일해봐요

2022-07-21 02:30 UTC, coby5502 commented on Gwayeon/Controllers/FruitCollectionViewCell.swift
> +    }
preferredLayoutAttributesFitting 함수는 UICollectionViewCell에 포함되어있으며 역할은 “Gives the cell a chance to modify the attributes provided by the layout object.”, layout object로부터 주어진 크기에 대해 한번 조정할 기회를 주는 것이다.

위 함수를 내가 원하는대로 재정의한 것인데 width는 flowLayout이 준 값으로 고정시키고 height만 동적으로 바꾸고 싶어서 size.heigt만 재조정을 하는 로직이다. 이 때 systemLayoutSizeFitting 함수는 “Returns the optimal size of the view based on its current constraints.” 현재 constraint를 준수하면서 가장 optimal한 크기를 반환해준다.

그러니까 컬렉션뷰의 아이템에 적용되는 레이아웃 객체인 UICollectionViewLayoutAttributes의 frame을 내가 재정의한 frame 값으로 바꿔치는 것이고, 위 함수에서 바꿔치는 값은 optimal 한 크기라는 것이다.

2022-07-21 02:33 UTC, coby5502 commented on Gwayeon/Controllers/FarmCollectionViewCell.swift
> +    static let cellId = "FarmCollectionViewCell"
[eab13ff](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22/commits/eab13ff9283e867f57bb5faf12aab60f6fb0a0e3)

반영완료

2022-07-21 02:36 UTC, yudonlee commented on Gwayeon/Globals/Extension/Color+Extension.swift
> +    static var grey001: UIColor {
discussion에 올려둬야 겠네요~

2022-07-21 02:37 UTC, merged