[ADD] DetailView 문자, 전화 Button UI, UIColor Extension
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #26
Opened 2022-07-19 10:51 UTC by DoAY9

## 🟣 관련 이슈
#20 

## 🟣 구현/변경 사항 및 이유
- 문자, 전화하기 버튼 구현 : Auto layout으로 width에 비례하게 설정
- UIColor Extension으로 메인 컬러 쓰기 쉽게 설정

## 🟣 PR Point
UIButton.Configuration 사용했어요! ios 15부터 쓸 수 있는 more customizable한 업데이트입니다.
https://zeddios.tistory.com/1291

## 🟣 참고 사항
![Simulator Screen Shot - iPhone 12 mini - 2022-07-19 at 19 50 20](https://user-images.githubusercontent.com/37866609/179733330-ce97f02a-b3d1-40aa-b56c-b352bfd57bc9.png)

2022-07-19 11:36 UTC, DoAY9 commented on Gwayeon/DetailViewController.swift
> +@IBDesignable
삭제해야함. preview 보려고 했던 용도.

2022-07-19 14:51 UTC, coby5502 reviewed
멋져요~ 언니

2022-07-19 14:51 UTC, coby5502 commented on Gwayeon/ColorExtension.swift
> +import Foundation
p1;
필요없는 import 입니다.

2022-07-20 00:26 UTC, hwiwonK commented
확인했어요! 피드백 받은거 고쳐주세용👍

2022-07-20 02:48 UTC, DoAY9 commented on Gwayeon/ColorExtension.swift
> +import Foundation
수정했습니다!

2022-07-20 03:01 UTC, HeejiSohn approved these changes
👍

2022-07-20 03:04 UTC, coby5502 approved these changes

2022-07-20 03:18 UTC, yudonlee requested changes
고생 많으셨습니다 😁
제가 말할 부분을 참고하셔서 추가적으로 배우셨으면 좋겠습니다.
그럼 다음 리뷰로 찾아오겠습니다

2022-07-20 03:18 UTC, yudonlee commented on Gwayeon/DetailViewController.swift
> +    }()
p2;
재사용될 버튼이 아니고, 해당 뷰에서만 사용될거라면 __private__ keyword를 사용해주세요 
```swift
lazy private var messageButton: UIButton = {
```

2022-07-20 03:18 UTC, yudonlee commented on Gwayeon/DetailViewController.swift
> +    func configureViewComponent() {
p2;
재사용되는 함수가 아니라면 __private__ keyword를 사용해주세요!
p4;
해당뷰가 viewcomponent들간에 layout을 설정하는걸로 보이는데 "set"이라는 키워드를 사용하는 건 어떨까요?
```swift
private func setViewComponentLayout()
```

2022-07-20 03:18 UTC, yudonlee commented on Gwayeon/DetailViewController.swift
> +        NSLayoutConstraint.activate(callButtonConstraints)
p3;
```swift
NSLayoutConstraint.activate()
```
를 사용해서 가독성을 높인점이 좋았습니다. 여기서 좀더 간결하게 하는 방법인 ForEach를 소개시켜드리고자 합니다.
```swift
[messageButton, callButton].forEach { button in 
    view.addSubView(button)
}
// ...
[callButtonConstraints, messageButtonConstraints].forEach { constraint in
        NSLayoutConstraint.activate(constraint)

}
```
즉석에서 친거라 오타가 있을수도 있지만, 이것을 사용해보는 건 어떨까요?  ☺️

2022-07-20 03:18 UTC, yudonlee commented on Gwayeon/SceneDelegate.swift
> +        window?.rootViewController = DetailViewController()
p1;
Conflict가 날 수도 있는만큼 원래 코드로 돌려주시면 좋겠습니다!

2022-07-21 07:19 UTC, closed without merging