Feat/24 recommend to friend view UI
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #28
Opened 2022-07-19 16:01 UTC by HeejiSohn

## 🟣 관련 이슈

#24 

## 🟣 구현/변경 사항 및 이유

-  내 과연에게 보내는 추천 한마디 구현

## 🟣 PR Point

## 🟣 참고 사항

<img width="378" alt="image" src="https://user-images.githubusercontent.com/96990839/179795748-b45ce129-a024-4484-812a-1cbf1d687fb4.png">

2022-07-20 00:06 UTC, coby5502 commented on Gwayeon/RecommendToFriendViewController.swift
> +
p1;

: 뒤에 한 칸 띄워주세요

2022-07-20 00:06 UTC, coby5502 commented on Gwayeon/RecommendToFriendViewController.swift
> +        completionButton.heightAnchor.constraint(equalToConstant: 50).isActive = true
p2;
버튼은 bottom에 고정하는거 어떨까요?

2022-07-20 01:19 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +
반영했습니다

2022-07-20 01:19 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        completionButton.heightAnchor.constraint(equalToConstant: 50).isActive = true
반영했습니다!

2022-07-20 02:14 UTC, hwiwonK commented on Gwayeon/RecommendToFriendViewController.swift
> +        label.text = "청송사과를"
p2;
'를'은 라벨을 따로 빼야할 것 같아요! 디자인 문제도 있지만, 나중에 데이터 받아와서 쓸 때 구분되어있는게 좋을 것 같아요

2022-07-20 02:21 UTC, hwiwonK reviewed
[3182515](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/318251587cc90b59105730634eecec6efb3193e4)
확인 했어요! 수고하셨습니다👍

2022-07-20 03:17 UTC, DoAY9 commented on Gwayeon/RecommendToFriendViewController.swift
> +        label.font = UIFont.systemFont(ofSize: 20, weight: .regular)
p4;
애플의 font style을 사용하면 좋을 것 같아요!
.preferredFont(forTextStyle: .title3)

2022-07-20 03:42 UTC, yudonlee requested changes
쏘니의 입장에서 왜 이렇게 구현할지 생각하면서 열심히 리뷰를 남겨보았습니다.
코멘트 주신것에서 다른 의견이면 꼭 댓글을 달아주세요!
코드외에도 첨언하자면 PR 제목은 "[PREFIX] 한글제목"을 지켜주세요!
PREFIX는 모두 대문자이며, 제목에는 한글로 좀더 직관적인 제목이 들어갔으면 좋겠습니다
그럼 다음 리뷰로 찾아오겠습니다 쏘니 😁

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +    }()
p2;
재사용될 것들이 아니라면 __private__ keyword를 사용해주세요~
p4;
클로저를 사용하면 코드한줄을 줄일수 있습니다.
```swift
private lazy var farmLabel: UILabel = { label in 
         label.text = "자연농원의"
         label.font = UIFont.systemFont(ofSize: 20, weight: .regular)
         return label
}(UILabel())
```

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +    lazy var fruitLabel: UILabel = {
p2;
재사용될 것들이 아니라면 _private keyword_를 사용해주세요~

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +        textView.font = UIFont.preferredFont(forTextStyle: .body)
p4;
저는 늘 
```swift
textView.font = UIFont.systemFont(ofSize: 20, weight: .bold)
```를 써와서 해당것들은 처음 보는데 폰트를 body로 바꾸는건가요?

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +    let textViewPlaceHolder = "가격, 맛, 배송에 대한 정보를 알려주면 내 친구들이 더 쉽게 살 수 있어요!"
p4;
dummy data로 사용될 것들이라면 최상단에 두거나, 해당 placeholder안에 그냥 넣는것은 어떨까요? 먼가 UIView의 subclass들인 UIButton, UITextView의 변수들이 나열되다가 string이 나열되니 어색한 느낌이 들어서요~ 개인적인 의견이라 이상하지 않다면 쓰셔도 될 것 같아요!

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +        view.addSubview(completionButton)
p3;
8줄이 동일한 역할을 하고 있는 만큼 ForEach를 쓰면 3줄로 조금더 간단해진답니다
```swift
[farmLabel, ...].forEach { component in 
    view.addsubView(component)
}
```

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +
p3;
```swift
let farmLabelConstraints = [
         farmLabel.topAnchor.constraint(equalTo: view.topAnchor, constant: 149),
         farmLabel.leftAnchor.constraint(equalTo: view.leftAnchor, constant: 16)
]
NSLayoutConstraint.activate(peoplePickLabelconstraints)
```
를 사용하면 코드가독성이 더 올라갈 것 같아요! 나중엔, ForEach를 사용해서 관리하기가 편한것 같아요


[83fd0d2](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/83fd0d2b04341d2877ff06bc513128e15314d791#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R90-R98f)를 참고하세용

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +
무슨 코드일까 했는데, 화면을 누르면 keyboard가 내려가는 걸 구현했네요! 좋습니다! 
p4;
다만 해당 함수를 따로 뺀다면, 좀더 가독성이 좋은 코드가 될 것 같습니다.

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +    func configureViewComponent() {
p2;
재사용될 것들이 아니라면 _private keyword_를 사용해주세요~
```swift
private func cnfigureViewComponent() { }
```
p4
제가 생각했을땐, configureViewConponent보단 set이라는 키워드를 사용해서 layout을 맞추는 함수라고 표현하는건 어떨까요?
```swift
private func setComponentLayouts()
```

2022-07-20 03:42 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +        guard let oldString = textView.text, let newRange = Range(range, in: oldString) else { return true }
p4;
guard let 사용 좋은 것 같습니다!

2022-07-20 03:54 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        label.text = "청송사과를"
[5be4477](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/5be4477d685c701b4c4b167a9b0fa46fa48011e8)
<img width="417" alt="image" src="https://user-images.githubusercontent.com/96990839/179893288-6f8be906-c56c-4519-a446-9931d10ff18d.png">

반영했습니다~

2022-07-20 06:45 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        textView.font = UIFont.preferredFont(forTextStyle: .body)
body는 17px입니다

따라서
``` swift
textView.font = UIFont.systemFont(ofSize: 17, weight: .regular)
```
와
``` swift
textView.font = UIFont.preferredFont(forTextStyle: .body)
```
가 같게됩니다

2022-07-20 07:02 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        label.font = UIFont.systemFont(ofSize: 20, weight: .regular)
[ae5dd97](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/ae5dd97647fa9a6098ff59f87aad0616a1a0cc1c)
반영했습니다!

2022-07-20 07:04 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +    }()
[0d2fcd4](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/0d2fcd46556eec6d00019496a9ac0d5ea6c9afe8)
반영했습니다!

2022-07-20 07:04 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +    lazy var fruitLabel: UILabel = {
[0d2fcd4](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/0d2fcd46556eec6d00019496a9ac0d5ea6c9afe8)
반영했습니다

2022-07-20 07:05 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +    let textViewPlaceHolder = "가격, 맛, 배송에 대한 정보를 알려주면 내 친구들이 더 쉽게 살 수 있어요!"
[0d2fcd4](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/0d2fcd46556eec6d00019496a9ac0d5ea6c9afe8)
반영했습니다
항상 좋은 의견 감사합니다 ^^

2022-07-20 08:11 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +    func configureViewComponent() {
[6e1193c](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/6e1193c5dd13d9752adc6150d8925ae63ab82946)
반영했습니다

2022-07-20 08:11 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +
[6e1193c](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/6e1193c5dd13d9752adc6150d8925ae63ab82946)
반영했습니다^^

2022-07-20 08:12 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        view.addSubview(completionButton)
[6e1193c](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/28/commits/6e1193c5dd13d9752adc6150d8925ae63ab82946)
반영했습니다

2022-07-20 14:59 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +        guard let oldString = textView.text, let newRange = Range(range, in: oldString) else { return true }
:)

2022-07-20 14:59 UTC, HeejiSohn commented on Gwayeon/RecommendToFriendViewController.swift
> +
:)

2022-07-21 05:54 UTC, coby5502 approved these changes
뭐지?

2022-07-21 07:16 UTC, HeejiSohn commented
> 뭐지?

머지(merge)뭐지(?)

2022-07-22 00:02 UTC, coby5502 approved these changes

2022-07-22 00:09 UTC, yudonlee approved these changes

2022-07-22 00:51 UTC, merged