[Feat] Friend List View 테이블 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #35
Opened 2022-07-20 01:44 UTC by hwiwonK

## 🟣 관련 이슈
#25 

## 🟣 구현/변경 사항 및 이유
- 테이블 뷰 구현 (custom Cell 적용)
- 테이블 타이틀

## 🟣 PR Point
- 코드가 더 정돈되었으면 좋겠다는 부분이 있다면 말씀해주세요

## 🟣 참고 사항
![image](https://user-images.githubusercontent.com/67336936/179877368-951ff9e2-41af-4c29-a584-cf9d0e5f804a.png)

2022-07-20 02:34 UTC, coby5502 reviewed
홧팅~

2022-07-20 02:34 UTC, coby5502 commented on Gwayeon/FriendList/FriendListViewController.swift
> +    }()
p2;
var 대신 private let 은 어떤가요?

2022-07-20 04:03 UTC, yudonlee requested changes
안녕하세요 메리, 메리의 입장에서 이런 코드는 왜 썼는지 고민해봤습니다.
제 리뷰는 저의 의견일뿐 답이 될수 없겠죠.
그래도 성심성의껏 리뷰했으니 반영하실 부분은 근거가 명확하다면 반영해주시면 좋을것 같습니다.
그럼 다음 리뷰로 찾아뵙겠습니다. 😁

2022-07-20 04:03 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewCell.swift
> +
p3;
3줄이 동일한 역할을 하고 있는 만큼 ForEach를 쓰면 조금더 가독성이 올라가요!
```swift
[nameLabel, ...].forEach { component in 
    view.addsubView(component)
}
```

2022-07-20 04:03 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        self.friendView.addArrangedSubview(friendTextLabel)
p3;
위 코드도 ForEach를 사용하면 더욱 간단해질 것 같아요!

2022-07-20 04:03 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        nameLabel.bottomAnchor.constraint(equalTo: self.centerYAnchor, constant: -2.5).isActive = true
p3;
```swift
let nameLabelConstraints = [
          nameLabel.leadingAnchor.constraint(equalTo: self.fruitImage.trailingAnchor, constant: 24)
          nameLabel.bottomAnchor.constraint(equalTo: self.centerYAnchor, constant: -2.5)
]
NSLayoutConstraint.activate(nameLabelConstraints)
```
를 사용하면 코드가독성이 더 올라갈 것 같아요! 나중엔, ForEach를 사용해서 관리하기가 편하답니다.


[83fd0d2](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/83fd0d2b04341d2877ff06bc513128e15314d791#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R90-R98f)를 참고하세용

2022-07-21 02:34 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +        let tableView = UITableView(frame: frame, style: UITableView.Style(rawValue: 0)!)
네 수정하겠습니다!

2022-07-21 02:37 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +
훨씬 깔끔해지는 방법이네요, 적용하겠습니다!

2022-07-21 12:07 UTC, HeejiSohn approved these changes
고생하셨습니다:)

2022-07-21 15:10 UTC, DoAY9 approved these changes

2022-07-22 00:13 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +        let tableView = UITableView(frame: frame, style: UITableView.Style(rawValue: 0)!)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR45
수정 완료했습니다

2022-07-22 00:13 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR78

constraint 들어가는 부분 모두 이런 방식으로 변경 했습니다!

2022-07-22 00:15 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    func render() {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR67
함수 이름을 직관적으로 바꿨고, 재사용이 안되는 것들은 모두 private 붙여줬습니다

2022-07-22 00:16 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR91

이 부분 외에도 forEach 활용할 수 있는 부분 활용해서 바꿔봤습니다!

2022-07-22 00:18 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +        tableView.register(FriendListViewCell.self, forCellReuseIdentifier: FriendListViewCell.cellId)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR47
tableView 선언 때 delegate, datasource 지정 등이 이루어지도록 했습니다!

2022-07-22 00:18 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +                                                ?? FriendListViewCell(style: UITableViewCell.CellStyle(rawValue: 0)!, reuseIdentifier: FriendListViewCell.cellId)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR106
반영했습니다!

2022-07-22 00:21 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    func render() {
FriendListViewCell에서 사용하는 컴포넌트들은 private으로 지정하면 
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR109
여기서 데이터를 넘겨줄 수가 없어서 private으로 하지 않았습니다!

2022-07-22 02:48 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    func render() {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ec3d5e6d1ac67bd432a1c0c3f13e492ec715e594

함수 호출하는 방식으로 cell에 데이터 넣도록 구현하였습니다

2022-07-22 03:23 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +    func setupFriendListView() {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R56
이름 변경 했습니다!

2022-07-22 03:26 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    let friendView : UIStackView = {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ec3d5e6d1ac67bd432a1c0c3f13e492ec715e594#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R46
수정했습니다!

2022-07-22 03:29 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        self.friendView.addArrangedSubview(friendTextLabel)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R58
반영했습니다!

2022-07-22 03:30 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        nameLabel.bottomAnchor.constraint(equalTo: self.centerYAnchor, constant: -2.5).isActive = true
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R72
반영했습니다!

2022-07-22 03:31 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +    var tableTitle : UILabel = {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR34

private 반영, tableTitleLabel로 이름 변경 완료 했습니다

2022-07-22 03:32 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    let nameLabel : UILabel = {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ec3d5e6d1ac67bd432a1c0c3f13e492ec715e594#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R23
private keyword 추가 했습니다!

2022-07-22 03:33 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    let friendNumberLabel : UILabel = {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ec3d5e6d1ac67bd432a1c0c3f13e492ec715e594#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R31
private keyword 추가 했습니다!

2022-07-22 03:34 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    let friendTextLabel : UILabel = {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ecb6cbe4458016e5d87eccd659a306d1cc186f7e#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R38
private keyword 추가 했습니다!

2022-07-22 03:37 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    let fruitImage = UIImageView()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ec3d5e6d1ac67bd432a1c0c3f13e492ec715e594#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R23
반영했습니당

2022-07-23 02:34 UTC, yudonlee approved these changes

2022-07-23 03:02 UTC, merged