[FEAT] Add RecoomendFarm UI
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #39
Opened 2022-07-20 03:42 UTC by YoonyoungL

## 🟣 관련 이슈
#37 

## 🟣 구현/변경 사항 및 이유
- InputSection에서 InputStyle을 받아 뷰를 만듭니다.
- 만든 InputSection들을 StackView로 쌓았습니다.

## 🟣 참고 사항
<img width="195" alt="image" src="https://user-images.githubusercontent.com/58019653/179890867-f3733395-e0d0-4600-99c5-2bf06d7f5c1b.png">

- 현재 CustomView(InputSection)를 사용하는데 추후 기능에 따라서 구조가 달라질 수 있습니다.

2022-07-20 04:32 UTC, yudonlee requested changes
안녕하세요 제리~ 대체로 신경쓰신 부분들이 많이 있어서 리뷰할게 별로 없네요!
그래도 제 개인적인 의견을 담아 리뷰를 해보았습니다. 
의문이 생기는 점은 댓글 달아주세요~~
다음 리뷰로 찾아뵙겠습니다

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/InputSection.swift
> +    }
enumeration을 사용해서 이렇게 간결하게 구현하신것에 감동받고 갑니다.👍

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/InputSection.swift
> +    }()
다른분들께도 소개시켜드린 클로저 사용을 소개시켜드릴게요.
```swift
private lazy var label: UILabel = { label in
          label.text = style.text
          label.font = UIFont.preferredFont(forTextStyle: .subheadline)
          return label
     }(UILabel())
```swift
해당 부분을 사용하면 코드 한줄이 감소합니다 😁

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/InputSection.swift
> +}
p2;
해당 extension은 Globals/Extension 폴더를 만들어두었으니, merge후 빼두시면 좋을 것 같습니다

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/RecommendFarmViewController.swift
> +        stackView.addArrangedSubview(recommendationSection)
p3;
안녕하세요 제리, 비슷한 상황이 반복되는 코드라서 ForEach를 소개시켜드릴까 합니다.
```swift
[cateGorySection, ...].forEach { component in 
    stackView.addArrangedSubView(component)
}
```

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/RecommendFarmViewController.swift
> +    private lazy var cateGorySection = InputSection(frame: .zero, style: .fruitCategory)
p4;
```swift
    private lazy var cateGorySection = InputSection(frame: .zero, style: .fruitCategory)
```
개인적으로 catagorySection을 변수명으로 사용하는 건 어떨까요?

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/RecommendFarmViewController.swift
> +    private func configureLayout() {
p4;
아무래도 저희 전체 코드스타일을 통일할려고 노력해야할 것 같아요! 
제가 생각했을땐 setConfigureLayout()과 같이 Layout을 세팅한다는 느낌을 주고 싶어서 Set keyword를 사용해보는 건 어떤가요!

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/RecommendFarmViewController.swift
> +        view.backgroundColor = .white
p3;
forEach를 쓴다면 코드가 좀더 간결하게 변한답니다.
```swift 
[titleLabel, ...].forEach { component in
    view.addSubview(component)
}
```

2022-07-20 04:32 UTC, yudonlee commented on Gwayeon/RecommendFarmViewController.swift
> +        ])
p3;
NSLayoutConstraint.activate를 써서 코드를 간결하게 한점 좋았습니다. 조금더 분리해서 사용하는 방법을 알려드릴게요!
```swift
let titleLabelConstraints = [
              titleLabel.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 30),
              titleLabel.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 16)
          ]
NSLayoutConstraint.activate(titleLabelConstraints)
```
입니다~ 이를 ForEach를 활용한다면 NSLayoutConstraint.activate를 한줄로 끝낼 수 있어 더욱 간결하게 사용가능하겠죠.
[83fd0d2](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/83fd0d2b04341d2877ff06bc513128e15314d791#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R90-R98f)를 참고하세용

2022-07-21 01:34 UTC, YoonyoungL commented on Gwayeon/RecommendFarmViewController.swift
> +    private func configureLayout() {
configure가 동사라서 setUI(), setLayout()이나 configureUI(), configureLayout()으로 하면 좋을 것 같네요.
일차적으로 합치고 팀원들과 함수명에 대해서 이야기 해봐요!

2022-07-21 13:02 UTC, HeejiSohn approved these changes
고생하셨습니당 :)

2022-07-21 13:02 UTC, HeejiSohn commented on Gwayeon/RecommendFarmViewController.swift
> +    }()
뒤에나오는 finishButton만 Stack View에 포함시키지 않으신 이유가 있나요? 
단순히 궁금해서 물어봅니다! :0

2022-07-21 14:58 UTC, DoAY9 commented on Gwayeon/RecommendFarmViewController.swift
> +    }()
Stack View 저도 써봐야겠어요!

2022-07-21 15:02 UTC, DoAY9 commented on Gwayeon/InputSection.swift
> +}
해당 카테고리의 특성에 따라 키보드 타입을 바꾸는 거 UX적으로 정말 훌륭합니다!

2022-07-22 03:40 UTC, yudonlee approved these changes

2022-07-22 03:47 UTC, merged