[FEAT] Detail view Button 새로 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #40
Opened 2022-07-20 08:32 UTC by DoAY9

## 🟣 관련 이슈
#38 

## 🟣 구현/변경 사항 및 이유
폴더링이 안된 초기 develop 브랜치에서 브랜치를 파고 작업해서 꼬일까봐
폴더링이 된 브랜치에서 새로 브랜치를 파고 작업했습니다.

## 🟣 PR Point

## 🟣 참고 사항
![Simulator Screen Shot - iPhone 13 - 2022-07-20 at 17 31 42](https://user-images.githubusercontent.com/37866609/179935963-5375853c-28a3-4663-af8a-2096ea53479e.png)

2022-07-21 14:08 UTC, HeejiSohn requested changes
고생하셨습니다 :)

2022-07-21 14:08 UTC, HeejiSohn commented on Gwayeon/Controllers/DetailViewController.swift
> +    }()
whiteView에 cornerRadius 를 아래에도 똑같이 30으로 줄지 팀원들과 디자인 수정할 때 함께 상의해봤으면 좋겠어요! 
지금은 background color가 핑크색이라 whiteView와 background 사이의 아래 부분이 어색하지 않은데 다른과일로 바뀔 때는 어색할 수 도 있을 것 같아요!

2022-07-22 02:22 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +    }()
네넹!

2022-07-22 02:30 UTC, DoAY9 commented on Gwayeon/SceneDelegate.swift
> +    ()
반영했습니다!

2022-07-22 02:32 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +        view.addSubview(fruitImageView)
[ef67878](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/40/commits/ef678788247e9f7ff1a3f96ab0a223e5cc6ab701#diff-03cd9b990e9d778778d1f28adbd9a648f2dde1f8e6283468cd300933bc83b164R85)에 반영했습니다

2022-07-22 02:35 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +        NSLayoutConstraint.activate(fruitImageViewConstraints)
[ef67878](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/40/commits/ef678788247e9f7ff1a3f96ab0a223e5cc6ab701#diff-03cd9b990e9d778778d1f28adbd9a648f2dde1f8e6283468cd300933bc83b164R131)에 반영했습니다!

2022-07-23 01:38 UTC, HeejiSohn approved these changes

2022-07-23 02:32 UTC, yudonlee approved these changes
확인했습니다!

2022-07-23 03:03 UTC, merged