[FEAT] 마이 페이지 상단 네비게이션 타이틀 및 나의 상태 뷰
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #41
Opened 2022-07-20 10:50 UTC by yudonlee

## 🟣 관련 이슈
#33 

## 🟣 PR Point
함수 naming, 변수 naming이 자연스러운지!
피그마에 있는대로, Navigation Bar와 사진 사이에 간격을 동일하게 주었는데 너무 많이 떨어진건 아닌지 의문이 갑니다~

## 🟣 참고 사항

<img src="https://user-images.githubusercontent.com/39371835/179963960-defc9efb-e516-4b8a-bcab-1f6c09ce66f4.png" width="394" height="600">

2022-07-20 14:38 UTC, coby5502 requested changes

2022-07-20 14:38 UTC, coby5502 commented on Gwayeon/Controllers/MyPageViewController.swift
>      }()
p5;
코드스타일 차이인거 같은데 lbl 쓰는게 좋나요? label 쓰는게 좋나요?

2022-07-20 14:38 UTC, coby5502 commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
p5;
$0을 쓴 이유가 있나요?

2022-07-21 15:53 UTC, HeejiSohn approved these changes
고생하셨습니다 :)

2022-07-21 15:53 UTC, HeejiSohn commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
NSMutableAttributedString 저도 사용해봐야겠네요!

p3;
forText: "100"에 .pointColor가 아닌 .mainColor가 아닐까 싶습니다 :)

2022-07-23 01:07 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
>      }()
[커밋](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/41/commits/e633f46f1e8015638ca16ce273c9a9d669d44571#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R11)에 반영되었습니다

2022-07-23 01:08 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
빠르게 개발하려고 하다보니 생각나는대로 쳐서 그런 것 같습니다:) 
수정했어요~
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/41/commits/747d0fe7956466700ecf798c511c0ca0aa07dbfd#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R25

2022-07-23 01:14 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/41/commits/430f983889dea8ef1c4c8d9ca401b4e85f74e366#diff-682d9f8556dd937412c2332b10fc8d14aa190bb72614c3fe77f94facd5eaca66R35 반영했습니다

2022-07-23 01:27 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
develop branch에서 merge받은 .mainColor를 사용해봤는데, 우선적으로 강제 추출이 돼서 일단 커밋을 되돌렸습니다! 나중에 반영하도록 하겠습니다. :)

2022-07-23 01:46 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }(UILabel())
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/41/commits/9df47687e577f2eec3d44ccff454aed7cb422073#diff-582c34ce85fa80358fcd4483681f15182198345d9e82911062e7a03bb33a613eR13로 반영되었습니다.
함수 인자 타입을 UIColor에서 UIColor?로 변경했습니다.
 Asset에서 UIColor를 만드는 initializer가 optional type이다보니 그걸 인자로 받았을때 강제추출이 되었던 현상입니다!

2022-07-23 01:53 UTC, yudonlee commented on Gwayeon/Controllers/MyPageViewController.swift
> +    }
|                                            largetitle쓰기 전                                            |                                            largetitle 쓴뒤                                            |
| :---------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------: |
| <img width="300" alt="largeTitle쓰지 않았다" src="https://user-images.githubusercontent.com/39371835/180585852-ba5e138f-e3b9-4dfa-93fe-d6a3133c6a5f.png"> |<img width="300" alt="largeTitle 쓴 것" src="https://user-images.githubusercontent.com/39371835/180585866-b3c1e470-2df1-4b03-9f38-ae706884f99e.png">|

로 차이가 나네요! 아무래도 정확한 구현을 위해서 largeTitle로 수정해야 할 것 같습니다. 대신 largeTitle 오른쪽에 버튼 배치가 저런식으로 되는 것이 합의가 안돼서 Backlog로 남겨두도록 할게요!

2022-07-24 04:19 UTC, DoAY9 approved these changes

2022-07-24 04:26 UTC, coby5502 approved these changes

2022-07-24 04:43 UTC, merged