[Feat] Friend list 뷰 footer, navigation bar 추가
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #47
Opened 2022-07-22 06:59 UTC by hwiwonK

## 🟣 관련 이슈
#36 

## 🟣 구현/변경 사항 및 이유
- footer 추가 (table과 함께 scroll 되도록 하기 위해 footer로 구현)
- navigation bar 구현 (navigation controller 추가하면 보입니다)

## 🟣 PR Point
- footer를 더 깔끔하게 구현할 수 있는 방법이 있다면, 혹은 footer외에 다르게 구현할 수 있는 방법이 있다면 알려주세요

## 🟣 참고 사항
<img src="https://user-images.githubusercontent.com/67336936/180381936-2e231ba9-e1bb-4c76-82c0-67526008eedd.png" width="200">

2022-07-24 04:24 UTC, YoonyoungL approved these changes
고생하셨습니다~👍

2022-07-24 04:24 UTC, YoonyoungL commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        nameLabel.translatesAutoresizingMaskIntoConstraints = false
p4;
이 부분도 위에 있는 코드처럼
```swift
[namelabel, fruitImage, friendNumberLabel].forEach{ component in
    component.translatesAutoresizingMaskIntoConstraints = false
}
``` 로 바꾸면 깔끔할 것 같아요!
팀원들이랑 코드 스타일 맞추고 변경해도 되니 그냥 넘어가셔도 됩니다!

2022-07-24 05:09 UTC, yudonlee requested changes
전체적으로 private variable 및 public function을 사용해서 구현하면 조금 더 좋은 코드가 되지 않을까
생각하여 제 의견을 적어봤습니다. 
제 의견은 단순한 의견일뿐 답이 될수 없겠죠. 다른 의견 있으시면 코멘트 남겨주세요!
그럼 다음 코드리뷰로 찾아뵙겠습니다.😁

2022-07-24 05:09 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    }()
P1;
외부에서 접근할 수 없도록 __private__ 으로 선언해주세요!

2022-07-24 05:09 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewController.swift
> +        cell.friendNumberLabel.text = String(friendsList[indexPath.row].friendsCount)
p2;
이부분은 해당 FriendViewCell.swift에서 설정해주도록 해야할 것 같습니다!
```swift
//.FriendListViewController.swift
cell.configure(with: friendList[indexPath.row]
```

```swift
//.FriendListViewCell.swift
func configure(with data: FriendData) {
    nameLabel.text = FriendData.name
}
```
위와 같이 private과 public func를 섞어서 사용하는 것이 좋을것 같습니다!

2022-07-24 05:09 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    static let cellId = "FriendCell"
p4;
개인적으로 
```swift
guard let cell = tableView.dequeueReusableCell(withIdentifier: FriendListViewCell.cellId,
                                                            for: indexPath) as? FriendListViewCell else { return UITableViewCell() }
```
에서 parameter 이름이 identifier이기 때문에 
```swift
    static let identifier = "FriendListViewCell"
```
이라고 하는편은 어떨지 제안해봅니다 😁아무래도 월요일날 이야기를 나눠봐야겠네요!

2022-07-24 15:27 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        label.textColor = UIColor(red: 246/256, green: 104/256, blue: 94/256, alpha: 1.00)
추후에 디자인 색깔 확정되면 수정하겠습니다!

2022-07-24 15:35 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +        nameLabel.translatesAutoresizingMaskIntoConstraints = false
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/c969a51601a7c2d15e106798ed826aefde028d87#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R74
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/c969a51601a7c2d15e106798ed826aefde028d87#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR119
코드가 훨씬 깔끔해질 것 같아서 적용해봤습니다!

2022-07-24 15:37 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    }()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/049fd761c4f635d0adf4245ecabdbd5d6e00b967#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0L23-R45
fruitImage, nameLabel, friendNumberLabel 모두 private 적용했습니다!

2022-07-24 15:38 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewCell.swift
> +    }()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/049fd761c4f635d0adf4245ecabdbd5d6e00b967#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R46-R49
적용했습니다!

2022-07-24 15:41 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +        cell.friendNumberLabel.text = String(friendsList[indexPath.row].friendsCount)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/c969a51601a7c2d15e106798ed826aefde028d87#diff-ed31d1249460d9184f3a361ecf5e131a5924c63bbc7ba06928247b88b9e52fb0R57-R62
저번에 코드리뷰를 받고 이런식으로 고쳐봤었는데, parameter로 data의 index를 넘겨주는 방식보다 data 자체를 넘겨주는 방식이 더 좋은 방식인지 궁금합니다!

2022-07-24 23:59 UTC, coby5502 approved these changes

2022-07-25 08:43 UTC, yudonlee commented on Gwayeon/FriendList/FriendListViewController.swift
> +        cell.friendNumberLabel.text = String(friendsList[indexPath.row].friendsCount)
아무래도 서버에서 받은 데이터들이 Model에 존재하고, 해당 데이터중 뷰에 필요한 데이터만 가지고 있는 ViewModel로 전환한 뒤 configure함수에 값들로 넘겨주는 MVVM 구조를 사용하기에,  "ViewModel 데이터"를 넘겨주는 구조로 구현했으면 좋겠습니다!

2022-07-25 08:43 UTC, yudonlee approved these changes

2022-07-25 10:56 UTC, hwiwonK commented on Gwayeon/FriendList/FriendListViewController.swift
> +        cell.friendNumberLabel.text = String(friendsList[indexPath.row].friendsCount)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/8321028f8a74549e1a37011ed3ef10a90ed4d7fa#diff-134e29c39f9050be9a85cd5d0c6a9d6959492c33ff1b4265bdc742548864f91fR166
그렇군요! MVVM 구조와 관련되어 있다는걸 생각해보지 못했네요👍 반영해서 수정했습니다!

2022-07-25 10:56 UTC, merged