[FEAT] 과일 상세페이지 CollectionView 가로 Scroll로 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #55
Opened 2022-07-25 13:52 UTC by DoAY9

## 🟣 관련 이슈
#31 

## 🟣 구현/변경 사항 및 이유
- Collection View 구현
- 가로 Scroll로 구현

## 🟣 PR Point
깔끔한 코드인지 한번 봐주세요!
+) 페이징 기능은 변경 예정입니다.

## 🟣 참고 사항
![Simulator Screen Shot - iPhone 13 - 2022-07-25 at 22 50 54](https://user-images.githubusercontent.com/37866609/180793662-2ddc5008-1c3c-4aad-a72b-08cdca9b865a.png)

2022-07-25 15:31 UTC, hwiwonK commented on Gwayeon/VIews/ReviewCollectionView.swift
> +//    ]
이 주석 부분은 나중에 사용할 예정이라 주석 처리 해놓으신 건가요??
사용하지 않을 코드라면 지워주는게 나을 것 같아요!

2022-07-25 15:57 UTC, hwiwonK commented on Gwayeon/VIews/ReviewCollectionView.swift
> +        }
``` swift
guard let cell = tableView.dequeueReusableCell(withIdentifier: FriendListViewCell.cellId,
                                                   for: indexPath) as? FriendListViewCell else { return UITableViewCell() }
```
전 이런식으로 casting error 발생시 UITableViewCell()을 return 하도록 구현했는데, assert로 구현하셨군요!
assert로 구현해도 에러를 피할 수 있는건가요? 어떤 방법이 더 좋은 방법일지 같이 공부해보면 좋을 것 같아요👍

2022-07-25 16:11 UTC, hwiwonK approved these changes
collection view 구현하시느라 정말 수고 많으셨습니다, collection view 마스터 에이든 최고!!!

2022-07-25 16:11 UTC, hwiwonK commented on Gwayeon/VIews/ReviewCollectionView.swift
> +        cell.authorLabel.text = authors[indexPath.item]
p2
저도 얼마 전에 배웠는데 view controller에서 cell의 컴포넌트에 직접 접근하는 것보다는, ReviewCollectionViewCell에 있는 컴포넌트는 private으로 설정하고, ReviewCollectionViewCell 클래스에서 정의한 데이터 적용 함수를 사용하는게 올바른 방법이라고 합니다!


https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/blob/8321028f8a74549e1a37011ed3ef10a90ed4d7fa/Gwayeon/FriendList/FriendListViewController.swift#L161-L169
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/blob/8321028f8a74549e1a37011ed3ef10a90ed4d7fa/Gwayeon/FriendList/FriendListViewCell.swift#L57-L62

2022-07-26 01:19 UTC, DoAY9 commented on Gwayeon/VIews/ReviewCollectionView.swift
> +//    ]
반영했습니다!

2022-07-26 12:01 UTC, yudonlee requested changes
수고하셨습니다~~ 👍 이제 더이상 많이 리뷰달 필요가 없네요!! 최고
폴더이름 VIews대신 Views로 꼭 반영 부탁드립니다!

2022-07-26 12:01 UTC, yudonlee commented on Gwayeon/VIews/ReviewCollectionViewCell.swift
> +    }()
p2;
__private__ 부탁..드려요!!

2022-07-26 14:41 UTC, DoAY9 commented on Gwayeon/VIews/ReviewCollectionView.swift
> +        }
헉 따라 쓴 거라 생각 못했네요; 빈 셀을 리턴하는 방식으로 변경하겠습니다!

2022-07-26 14:52 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +        return name
오! 반영했습니다!

2022-07-26 14:53 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +
잊지 않을 거에요..!

2022-07-26 14:54 UTC, DoAY9 commented on Gwayeon/SceneDelegate.swift
> +//        window?.rootViewController = DetailViewController()
반영했습니다!

2022-07-26 14:54 UTC, DoAY9 commented on Gwayeon/VIews/ReviewCollectionView.swift
> +//    ]
넵 반영했습니다! 오타가 났네요ㅋㅋㅋ

2022-07-26 14:55 UTC, DoAY9 commented on Gwayeon/VIews/ReviewCollectionViewCell.swift
> +        }
반영했습니다~

2022-07-26 14:56 UTC, DoAY9 commented on Gwayeon/VIews/ReviewCollectionViewCell.swift
> +    }()
반영했습니다!

2022-07-27 05:44 UTC, yudonlee approved these changes
고생하셨어요!

2022-07-27 06:25 UTC, merged