[FEAT] username setting view UI 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #56
Opened 2022-07-25 15:59 UTC by HeejiSohn

## 🟣 관련 이슈
#52
## 🟣 구현/변경 사항 및 이유
username setting view UI 구현

## 🟣 PR Point
textfield border style을 underline에서 rectangle로 바꾸었습니당

## 🟣 참고 사항
<img width="200" alt="image" src="https://user-images.githubusercontent.com/96990839/180822166-939ac1a9-87e8-41c5-9632-b3ab46f0d701.png">

2022-07-25 16:16 UTC, hwiwonK commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +        usernameTextfield.translatesAutoresizingMaskIntoConstraints = false
p1
필요 없는 코드가 들어가있는 것 같아요, 밑 부분과 겹치네요!

2022-07-25 16:18 UTC, hwiwonK commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +            usernameTextfield.bottomAnchor.constraint(equalTo: usernameTextfield.topAnchor,constant: 42), usernameTextfield.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16), userna
p2
개행이 있다면 훨씬 코드가 보기 좋아질 것 같아요!

2022-07-26 00:02 UTC, coby5502 approved these changes
😀

2022-07-26 00:37 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +        usernameTextfield.translatesAutoresizingMaskIntoConstraints = false
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/56/commits/ccd1d2651d58eebe90ea6d41a7b83f14a649e145#diff-0580946364e718fb976e0a55c40a28fbffab87a8ebc57379f2ac129e3e6fef65L46
반영했습니다:)

2022-07-26 00:39 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +            usernameTextfield.bottomAnchor.constraint(equalTo: usernameTextfield.topAnchor,constant: 42), usernameTextfield.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16), userna
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/commit/ccd1d2651d58eebe90ea6d41a7b83f14a649e145#diff-0580946364e718fb976e0a55c40a28fbffab87a8ebc57379f2ac129e3e6fef65R56-R60
반영했습니다:)

2022-07-26 09:24 UTC, hwiwonK approved these changes

2022-07-26 09:25 UTC, hwiwonK commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +            usernameTextfield.bottomAnchor.constraint(equalTo: usernameTextfield.topAnchor,constant: 42), usernameTextfield.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16), userna
확인했습니다!!

2022-07-26 12:03 UTC, yudonlee requested changes
수고하셨습니다! 고차함수 인상깊네👍

2022-07-26 12:03 UTC, yudonlee commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +    }()
question;
어떤건 return 전 개행이 있고 어떤건 없는데 의도하신건가요?
통일하면 더 보기 좋을것 같아요!

2022-07-26 12:03 UTC, yudonlee commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +        }
p2;
두개를 붙여서 사용해도 되지 않을까요?
```swift
 [usernameLabel, usernameTextfield, nextButton].forEach { component in
              view.addSubview(component)
              component.translatesAutoresizingMaskIntoConstraints = false
          }
```

2022-07-27 05:59 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +    }()
의도 아닙니다
수정했습니다 :)
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/56/commits/b167ce925bdf96f7d791fc9e82eea373b49b7bd8#diff-0580946364e718fb976e0a55c40a28fbffab87a8ebc57379f2ac129e3e6fef65L22

2022-07-27 05:59 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
> +        }
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/56/commits/b167ce925bdf96f7d791fc9e82eea373b49b7bd8#diff-0580946364e718fb976e0a55c40a28fbffab87a8ebc57379f2ac129e3e6fef65L22
반영했습니다 :)

2022-07-27 06:03 UTC, yudonlee approved these changes

2022-07-27 06:44 UTC, merged