[FEAT] 메인화면 빈화면
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #63
Opened 2022-07-26 02:27 UTC by coby5502

## 🟣 관련 이슈
#62

## 🟣 구현/변경 사항 및 이유
- 메인화면에서 과일이 없을 때 뷰

## 🟣 PR Point
- 전체 태그 미리 선택되어 있는 것은, 다른 브랜치에서 작업했습니다~

## 🟣 참고 사항

![simulator_screenshot_92BC2E9D-6A66-4A90-B5F2-78F596189AFC](https://user-images.githubusercontent.com/57849386/180909404-8e7dba88-bcce-4eaa-a1d4-1c1f4a49bb9e.png)

2022-07-26 12:12 UTC, yudonlee approved these changes
수고하셨습니다 👍

2022-07-26 12:12 UTC, yudonlee commented on Gwayeon/Controllers/HomeViewController.swift
> +        }
데이터가 있고 없고에 따라서 View가 Hidden되고, 안되고가 정해지겠네요!
다만, 데이터가 비어있고, 데이터가 후에 추가되더라도 해당 뷰가 Life Cycle상으로 사라지고 다시 로딩되지 않는 한 상태가 변하지 않을 것 같아서 그부분만 추후에 고려하면 될 것 같습니다!

2022-07-27 00:47 UTC, hwiwonK approved these changes
수고 많으셨습니다~!👍

2022-07-27 00:47 UTC, hwiwonK commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        }
p4
collection view가 아닌데 setCollectionViewLayout 라고 하신 이유가 있나요??

2022-07-27 00:47 UTC, hwiwonK commented on Gwayeon/Controllers/HomeViewController.swift
> +            fruitEmptyView.isHidden = true
isHidden 으로 뷰를 안보이게 하는 방법도 있군요! 저도 참고해서 코드 작성해봐야겠네요~~!

2022-07-27 07:10 UTC, YoonyoungL requested changes
안녕하세요 코비
피그마에 있는 문장과 달라서 Request changes 남겨놓았습니다!
혹시 바꾸신 이유가 있을까요?

2022-07-27 07:10 UTC, YoonyoungL commented on Gwayeon/Controllers/FruitEmptyView.swift
> +    }()
p2;
피그마에 있는 화면과 문장이 달라서 문장 변경해주시면 좋을 것 같아요!
<img src="https://user-images.githubusercontent.com/58019653/181183659-c8cbd153-9d7e-42bf-bf76-8bbf818c69f3.png" width="150"/>

2022-07-27 07:23 UTC, HeejiSohn approved these changes
PR 올리실때 이미지 사이즈 width 200으로 조절 부탁드립니다!
수고하셨습니다!

2022-07-27 07:23 UTC, HeejiSohn commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        emptyLabel.translatesAutoresizingMaskIntoConstraints = false
p3;
해당 부분도 붙여서 사용할 수 있을 것 같습니다:)
 ``` swift
[emptyLabel, recommendLabel, findFriendLabel].forEach { component in
             self.addSubview(component)
             component.translatesAutoresizingMaskIntoConstraints = false
         }

2022-07-27 07:23 UTC, HeejiSohn commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.textColor = .red001
mainColor 사용 부탁드립니다!

2022-07-27 07:23 UTC, HeejiSohn commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.text = "과연을 추가하여 과일을 추천받아 보세요!"
p5;
recommendLabel은 어떤 label을 지정하는지 한번에 이해하기가 쉽지 않아서
recommendAddFriendLabel은 어떨까요?

2022-07-27 10:47 UTC, DoAY9 approved these changes
수고하셨습니다~!

2022-07-27 10:47 UTC, DoAY9 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +    }()
p3;
같은 스타일의 폰트인데 하나의 label에 합쳐 줄바꿈을 쓰는 대신 2개의 laberl로 나누신 이유가 있으실까용?

2022-07-27 10:47 UTC, DoAY9 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.font = UIFont.systemFont(ofSize: 17, weight: .light)
p3;
weight가 light면 잘 안 보일 것 같습니다..! HIG에서 regular 이상의 weight를 쓰라는 말이 있어 알려드립니다~

In general, avoid light font weights to help maintain readability. For example, if you’re using system-provided fonts, u**se Regular, Medium, Semibold, or Bold font weights, and avoid Ultralight, Thin, and Light font weights,** which can be difficult to see, especially when text is small.

[https://developer.apple.com/design/human-interface-guidelines/foundations/typography/](url)

2022-07-28 00:28 UTC, coby5502 commented
> 안녕하세요 코비 피그마에 있는 문장과 달라서 Request changes 남겨놓았습니다! 혹시 바꾸신 이유가 있을까요?

아직 문장이 확정이 아닌거 같아서, 편한대로 적었어요...
피그마대로 다시 적겠습니다...!

2022-07-28 00:29 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.font = UIFont.systemFont(ofSize: 17, weight: .light)
감사합니다!!! 배워가요

2022-07-28 00:29 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +    }()
라벨사이에 간격을 주기 편해서 그랬습니다~

2022-07-28 00:30 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.textColor = .red001
텍스트 색깔이 또 다르길래 써봤습니다 mainColor로 통일할게요...!

2022-07-28 00:36 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        }
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +    }()
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        }
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        emptyLabel.translatesAutoresizingMaskIntoConstraints = false
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.textColor = .red001
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.text = "과연을 추가하여 과일을 추천받아 보세요!"
이건 보류~

2022-07-28 00:37 UTC, coby5502 commented on Gwayeon/Controllers/FruitEmptyView.swift
> +        label.font = UIFont.systemFont(ofSize: 17, weight: .light)
[e8cb551](https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/63/commits/e8cb55120597bff170a835fca0c799686b5fd768)
반영했습니다.

2022-07-28 01:13 UTC, YoonyoungL commented on Gwayeon/Controllers/FruitEmptyView.swift
> +    }()
확인했습니다!

2022-07-28 01:13 UTC, YoonyoungL approved these changes

2022-07-28 01:13 UTC, merged