[FEAT] MyPage 나의 추천 농장, 구매한 과일 별도 CollectionViewCell 생성
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #66
Opened 2022-07-26 07:57 UTC by yudonlee

## 🟣 관련 이슈

#64 

## 🟣 구현/변경 사항 및 이유
<img src=https://user-images.githubusercontent.com/39371835/180953913-95542d6a-2c85-43bc-8530-a1932f5370dc.gif, width="200")

기존에 구현한 BuyingListCollectionViewCell을 커스텀해서 MyPageFruitListCell을 만들었습니다.
MyPageListCell에서 "과연에게 추천하기 버튼", "자신이 추천한 한마디" 이 두개의 UI를 동일한 위치에 배치시켰습니다.
이들은 Segment Control 상태에 맞춰서 hidden 되는 방식으로 구현했는데 다른 해결방법 있으신가요?

## 🟣 PR Point

## 🟣 참고 사항
Develop에서 merge후 작업하느라.. 커밋을 분리 못했어요! 죄송합니다.

2022-07-27 06:18 UTC, YoonyoungL reviewed
코드 스타일을 주로 확인했습니다! 고생하셨어요

2022-07-27 06:18 UTC, YoonyoungL commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    private var fruitImageView: UIImageView = { imageView in
p4;
한 파일 내에서 클로저를 쓰는 방식과 다른 방식이 혼합되어 있는데
하나로 통일하는 게 좋아 보입니다!

2022-07-27 06:18 UTC, YoonyoungL commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    @objc private func recommendToGwayButtonClicked(_ sender: Any) {
p3;
함수명이 바로 이해하기 힘들 것 같아요
Gway가 과연을 의미하는 건가요?
``` swift
@objc private func recommendToGwayeonButtonClicked(_ sender: Any)
```
``` swift
@objc private func recommendToFriendButtonClicked(_ sender: Any)
```
로 변경하는게 좋아 보입니다.

2022-07-27 06:18 UTC, YoonyoungL commented on Gwayeon/Controllers/MyPageViewController.swift
> +//        collectionView.register(FarmCollectionViewCell.self,
p3;
사용하지 않는 코드는 삭제하고 합쳐요 😀

2022-07-27 06:18 UTC, YoonyoungL commented on Gwayeon/RecommendToFriendViewController.swift
> +
p4;
빈줄 삭제하면 좋을 것 같아요

2022-07-27 08:04 UTC, HeejiSohn requested changes
수고하셨습니당 :-)

2022-07-27 11:03 UTC, DoAY9 approved these changes

2022-07-27 14:26 UTC, coby5502 approved these changes

2022-07-28 01:21 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    private var fruitImageView: UIImageView = { imageView in
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/66/commits/11d2ef102e88f85ebbb2cca90ca6c9a4141feaf2
반영했습니다

2022-07-28 01:21 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    @objc private func recommendToGwayButtonClicked(_ sender: Any) {
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/66/commits/11d2ef102e88f85ebbb2cca90ca6c9a4141feaf2 반영했습니다

2022-07-28 01:21 UTC, yudonlee commented on Gwayeon/RecommendToFriendViewController.swift
> +
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/66/commits/11d2ef102e88f85ebbb2cca90ca6c9a4141feaf2 반영했습니다.

2022-07-28 01:21 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    }()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/66/commits/11d2ef102e88f85ebbb2cca90ca6c9a4141feaf2 반영했습니다.

2022-07-28 01:22 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    }()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/66/commits/20706c8b0952aa9a880c0bd0ce01939e7d91feff 반영했습니다.

2022-07-28 01:26 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    }
MyPageViewController에 Custom CollectionViewCell이 존재하고, Cell안에 버튼이 존재합니다. 
Cell안에 +버튼을 누르면 MyPageViewController에서 RecommendFarmViewController, RecommendToFriendViewController로 이동하게 되기 때문에 해당 함수를 호출합니다!

2022-07-28 01:31 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    }
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22#discussion_r926198125
코비의 댓글을 참고했습니다!

2022-07-28 01:31 UTC, yudonlee commented on Gwayeon/Controllers/MyPageFruitListCollectionViewCell.swift
> +    }
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/22#discussion_r926198125
코비의 댓글을 첨부합니다!

2022-07-28 01:34 UTC, HeejiSohn approved these changes

2022-07-28 01:35 UTC, merged