[FEAT] 유저 프로필 완성 뷰 UI 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #78
Opened 2022-07-28 00:42 UTC by HeejiSohn

## 🟣 관련 이슈
#65

## 🟣 구현/변경 사항 및 이유

유저 프로필 완성 뷰 UI 구현 및 랜덤 프로필 이미지 생성

## 🟣 PR Point

## 🟣 참고 사항
<img width="200" alt="image" src="https://user-images.githubusercontent.com/96990839/181396081-3d137b9f-7aa6-4c93-b238-d1f7cb206b9d.png">

2022-07-28 01:01 UTC, coby5502 approved these changes
메롱

2022-07-28 01:01 UTC, coby5502 commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +    }()//피그마에 있는 shadow가 좀 구린것같아서 디자인 수정 후 나중에 추가 예정
p2;
따로 빼는거 어떤가요?

2022-07-28 01:37 UTC, HeejiSohn commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +    }()//피그마에 있는 shadow가 좀 구린것같아서 디자인 수정 후 나중에 추가 예정
나중에 하겠습니다^^

2022-07-28 01:43 UTC, yudonlee requested changes
쏘니, enum으로 빼는거 해보시는 것도 좋을것 같아요!

2022-07-28 01:43 UTC, yudonlee commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +    }()//피그마에 있는 shadow가 좀 구린것같아서 디자인 수정 후 나중에 추가 예정
enumeration을 사용해보는건 어떤가요? enum을 통해서 과일 카테고리및 imageView를 넣어두면 좋을것 같아요!

2022-07-28 01:43 UTC, yudonlee commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +
개행만 빼면 좋을것 같아요!

2022-07-28 01:43 UTC, yudonlee commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +        }
```swift
view.addSubviews(profileImageView, usernameLabel, ...)
```
이걸로 대체하는것도 괜찮은 것 같아요!

2022-07-28 01:43 UTC, yudonlee commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +    }()//피그마에 있는 shadow가 좀 구린것같아서 디자인 수정 후 나중에 추가 예정
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/39/files#diff-2e2bcc98b6b4b532785b045de317354363266605438cef5014af6e940b5e1262R10-R45

2022-07-28 13:22 UTC, hwiwonK approved these changes
확인했습니다, 수고 많으셨습니다~!!

2022-07-29 01:01 UTC, yudonlee approved these changes

2022-07-29 01:15 UTC, HeejiSohn commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +        }
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/78/commits/864c94d1b3d4a5042fbdb3b624b2a551eec30a9b
반영했습니다 :)

2022-07-29 01:15 UTC, HeejiSohn commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +
반영했습니다 :)

2022-07-29 01:16 UTC, merged