[Feat] 이름 입력과 프로필 완성 네비게이션 링크
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #84
Opened 2022-07-28 15:15 UTC by HeejiSohn

## 🍑 관련 이슈

#83

## 🍑 구현/변경 사항 및 이유
이름 입력 뷰와 프로필 완성뷰 네비게이션 링크 연결

## 🍑 PR Point

## 🍑 참고 사항
<img width="200" alt="image" src="https://user-images.githubusercontent.com/96990839/181573267-f67774ef-2015-4739-8b61-86c16aaaa18b.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/96990839/181573182-42635246-6fcf-4166-8550-b55c45c3efd3.png">

2022-07-29 00:23 UTC, coby5502 approved these changes
짱

2022-07-29 00:23 UTC, coby5502 commented on Gwayeon/Controllers/UsernameSettingViewController.swift
p5;
setNavigation() 은 어떤가요?

2022-07-29 01:44 UTC, yudonlee requested changes
중복만 해결하면 될 것 같습니다!

2022-07-29 01:44 UTC, yudonlee commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +            component.translatesAutoresizingMaskIntoConstraints = false        }
p1;
이거 왜 똑같은 코드가 같이 있죠?
밑에꺼는 삭제해야 할 것 같아요!

2022-07-29 02:10 UTC, HeejiSohn commented on Gwayeon/Controllers/UserProfileCompletionViewController.swift
> +            component.translatesAutoresizingMaskIntoConstraints = false        }
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/84/commits/d116567c8c230b255a5b7b384255faff90bccf6c
반영했습니다 :)

2022-07-29 02:11 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
나중에 다같이 맞춰봐요!
TODO로 남겨두겠습니당

2022-07-29 14:07 UTC, hwiwonK approved these changes
수고 많으셨습니다😊

2022-07-29 14:07 UTC, hwiwonK commented on Gwayeon/Controllers/UsernameSettingViewController.swift
>          configureLayout()
p2;
저희 setLayout()으로 이름 통일하기로 했었어서, 이 부분 수정 부탁드립니다!

2022-07-29 15:48 UTC, yudonlee approved these changes

2022-07-30 02:51 UTC, HeejiSohn commented on Gwayeon/Controllers/UsernameSettingViewController.swift
>          configureLayout()
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/84/commits/9562a3030b8a7ea33650811e6d3e2995600a3ed6
반영했습니다 :)

2022-07-30 02:51 UTC, merged