[Feature]: 상세 페이지 Half Modal 구현
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #94
Opened 2022-07-29 09:20 UTC by DoAY9

## 🍑 관련 이슈
#68 

## 🍑 구현/변경 사항 및 이유
- modal 버튼 누르면 half modal view가 올라옵니다.
- 아니요 버튼 누르면 내려갑니다.

## 🍑 PR Point
- modal 버튼은 사라질 예정입니다. 지금은 ui 확인용입니다.(전화 끊으면 자동으로 올라오게 구현 후 버튼 삭제 예정)
- UISheetPresentationController를 사용했는데 Sheet의 height를 바꾸는 방법을 못 찾았습니다..
- UILabel의 행간을 포함한 전체적인 디자인 디테일은 수정할 예정입니다.

## 🍑 참고 사항
<img src="https://user-images.githubusercontent.com/37866609/181727679-805ed226-f627-43da-aedf-cf2f5cf777f5.png" width="200" />

2022-07-29 16:00 UTC, hwiwonK approved these changes
모달을 다루는 방법 잘 알아갑니다, 수고 많으셨습니다!😊

2022-07-29 16:05 UTC, yudonlee requested changes
수고하셨습니다. 코멘트 참고해서 수정 바랍니다!😁

2022-07-29 16:05 UTC, yudonlee commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +    }
p1;
private keyword를 사용해주세요!
p3;
해당 함수의 이름은 수정될 필요가 있는 것 같아요!
```swift
@objc func cancelButtonClicked()
```

```swift
@objc func didCancelButtonClicked()
```
와 같이 어떤 버튼을 클릭했을때 사용되는 함수인지 알면 좋을것 같아요

2022-07-29 16:05 UTC, yudonlee commented on Gwayeon/Controllers/DetailViewController.swift
> +    // UIButton.Configuration: ios 15에서 업데이트된 기능. more customizable.
개인적인 메모는 커밋시 코드상에서 지워주세요!

2022-07-29 16:05 UTC, yudonlee commented on Gwayeon/Controllers/DetailViewController.swift
> +    }
p2;
해당 함수도, 어떤 버튼을 눌렀을때 호출되는 함수인지 명확한 naming이 필요해보입니다.

2022-07-29 16:05 UTC, yudonlee commented on Gwayeon/Controllers/DetailViewController.swift
>          }
p2;
저희가 Extension으로 만든 
```swift
addSubviews(fruitImageView, ...)
```
를 써보는건 어떤가요?

2022-07-29 16:05 UTC, yudonlee commented on Gwayeon/SceneDelegate.swift
> +        window?.rootViewController = DetailViewController()
테스트 용도로 사용된 viewController 코드는 SceneDelegate에서 다시 discard 시켜주세요!

2022-07-30 05:28 UTC, DoAY9 commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +        configureViewComponent()
반영했습니다~!

2022-07-30 05:28 UTC, DoAY9 commented on Gwayeon/SceneDelegate.swift
> +        window?.rootViewController = DetailViewController()
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/SceneDelegate.swift
> +        window?.rootViewController = DetailViewController()
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +    }
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +    // UIButton.Configuration: ios 15에서 업데이트된 기능. more customizable.
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +    }
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/SceneDelegate.swift
> +        window?.rootViewController = DetailViewController()
반영했습니다~!

2022-07-30 05:30 UTC, DoAY9 commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +        configureViewComponent()
반영했습니다~!

2022-07-30 06:51 UTC, HeejiSohn approved these changes
에이든 번호 알게되어 영광입니다:)

2022-07-30 08:47 UTC, coby5502 approved these changes

2022-07-30 08:47 UTC, coby5502 commented on Gwayeon/Controllers/DetailViewController.swift
> +
번호를 퍼블릭으로 공개하는군요 ㅎㅎ

2022-07-30 14:20 UTC, yudonlee requested changes
코멘트 참고바랍니다!

2022-07-31 12:30 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +        self.tabBarController?.tabBar.isHidden = true
상세 페이지에 탭바 없애기로 해서 숨겨놓았어용..

2022-07-31 12:30 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +    func showMyViewControllerInACustomizedSheet() {
넵 반영했습니다!

2022-07-31 12:31 UTC, DoAY9 commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +        }
반영했습니다!

2022-07-31 12:32 UTC, DoAY9 commented on Gwayeon/Controllers/BottomSheetViewController.swift
> +
어머 반영했습니다!

2022-07-31 12:32 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
> +
으아ㅏㅏㅏ아악 세상에나ㅏㅏㅏㅏ!
반영했습니다!

2022-07-31 12:33 UTC, DoAY9 commented on Gwayeon/Controllers/DetailViewController.swift
>          }
반영했습니다!

2022-07-31 13:57 UTC, yudonlee approved these changes

2022-07-31 16:26 UTC, merged