[Feat] 파이어베이스 기본적인 모델, 다시 만들기
DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori pull request #99
Opened 2022-07-30 07:33 UTC by yudonlee

## 🍑 관련 이슈
#88 

## 🍑 구현/변경 사항 및 이유
Relation DB를 구축한 이유는, 각 Document ID를 활용하여 바로 문서를 참조하기 위함인데, pinCode와 userName이라는 field를 통해 Document를 가져오는 불필요한 depth가 추가됐다. 이로인해 관계형 디비의 장점을 살리지 못하였기에 이를 해결하기 위해 구현하였다. 

## 🍑 PR Point
모델을 보고, 각자 맡은 뷰에서 어떤 ViewModel을 가져야 할 지 생각해보면 좋을 것 같다!

## 🍑 참고 사항

<img width="860" alt="스크린샷 2022-07-30 오후 4 32 51" src="https://user-images.githubusercontent.com/39371835/181880118-be851208-9ca5-4ba8-bc92-03d85d2c9697.png">

2022-07-30 14:22 UTC, YoonyoungL requested changes
안녕하세요 닐 저는 Fruit와 Recommend를 잘 봐야겠네요.
Fruit에 fruitCategory는 코드를 가지기로 한 것으로 기억해서 Int가 좋지 않을까 합니다!

2022-07-30 14:22 UTC, YoonyoungL commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
p2;
fruitCategory는 Int인게 좋지 않을까요?

2022-07-30 17:25 UTC, coby5502 commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
좋은 방법을 같이 찾아봐요. 내일 게더에서 회의 한 번 하는거어때요?
enum 쓰는 것두 찾아보고...!

2022-07-30 17:28 UTC, coby5502 requested changes
저랑 변수명이라던지, DB 구조에 대해서 조금 회의할 시간이 필요할 거 같습니다.
편한 시간 말해주세요 유돈 리~ 빠를 수록 좋아요!

2022-07-30 17:28 UTC, coby5502 commented on Gwayeon/Models/User.swift
> +    var recommends: [String]
```suggestion
    var uid: String
    var username: String
    var friends: [String]?
    var recommends: [String]?
```
p1;
친구와 추천이 없을 때를 고려해야하지 않을까여?

2022-07-30 17:28 UTC, coby5502 commented on Gwayeon/SceneDelegate.swift
p1;
TestViewController는 언제 날려버릴 생각인가염

2022-07-30 17:58 UTC, HeejiSohn approved these changes
고생하셨습니다:)
그런데 userid는 사용자에게 직접 입력받는건 아니죠?

2022-07-30 17:58 UTC, HeejiSohn commented on Gwayeon/FirebaseManagerTestUI/TestViewController.swift
>      }()
실제로는 userid를 사용자에게 직접 입력받는건 아니죠?

2022-07-31 04:10 UTC, yudonlee commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
enum으로 image와 숫자들을 넣는 방법으로 개선해야 겠네요!

2022-07-31 04:14 UTC, yudonlee commented on Gwayeon/FirebaseManagerTestUI/TestViewController.swift
>      }()
네~ 자체적으로 앱내부에서 userId를 가지고 있을 예정입니다!

2022-07-31 04:15 UTC, yudonlee commented on Gwayeon/SceneDelegate.swift
다른 분들 쓰시기 편하도록 사용법 매뉴얼 처럼 둔건데 만약 다른분들이 전부 익숙해지셨으면 후에 삭제할게요!

2022-07-31 04:18 UTC, yudonlee commented on Gwayeon/Models/User.swift
> +    var recommends: [String]
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/99/commits/2164788d6b941d03c9dd6462e927d396e846021e 반영했습니다~

2022-07-31 04:19 UTC, yudonlee commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
일단 전체적으로 merge한 뒤, 해야할 것 같습니다!

2022-07-31 04:39 UTC, yudonlee commented on Gwayeon/SceneDelegate.swift
https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/99/commits/b829ff2b5c12973733942ec5dcbdcd630f55ed0d#diff-3f85b2c4a35918b079f1e7a1fca5b7e5952399c042967d495f99569338f8b579L18-L19 다른 이야기였네요! Scenedelegate 수정완료~

2022-07-31 05:13 UTC, coby5502 approved these changes

2022-07-31 05:55 UTC, YoonyoungL commented on Gwayeon/Models/Fruit.swift
> +    let fruitCategory, fruitName, farmName, farmTelNumber: String
확인했습니다. Approve로 변경할게요 TODO 달아주시면 나중에 확인하기 좋을 것 같습니다!

2022-07-31 05:55 UTC, YoonyoungL approved these changes

2022-07-31 05:57 UTC, merged